version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - D:\Projetos\timesheet\api:/api
    restart: always
    depends_on:
      - redis
    links:
      - redis
    expose:
      - "3000"
    networks:
      - redis
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-tests
  #   command: npm start
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - D:\Projetos\timesheet\tests:/tests
  #   depends_on:
  #     - app
  #   networks:
  #     - redis
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:${REDIS_PORT}"
    networks:
        - redis
networks:
  redis:
    driver: bridge
