version: "3.8"
services:
  app:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - D:\Projetos\timesheet:/app
    restart: always
    depends_on:
      - redis
    links:
      - redis
    networks:
      - redis
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:${REDIS_PORT}"
    networks:
        - redis
networks:
  redis:
    driver: bridge